const icons = { check:'✓✓' };
    const chats = [
      {id:'laura', name:'Laura Medina', initials:'LM', cls:'a1', online:true, time:'10:42', preview:'Perfecto, ¡nos vemos allí! ✨', unread:2, type:'chat', messages:[{from:'them', text:'¡Hola, Dani! ¿Cómo va el proyecto?', time:'10:32'}, {from:'me', text:'¡Muy bien! Ya terminé la propuesta de la nueva interfaz.', time:'10:36'}, {from:'them', text:'Me encanta. ¿Me la compartes para revisarla antes de la reunión?', time:'10:38'}, {from:'me', file:true, text:'Propuesta_NovaChat.pdf', sub:'PDF · 3.2 MB', time:'10:40'}, {from:'them', text:'Perfecto, ¡nos vemos allí! ✨', time:'10:42'}]},
      {id:'equipo', name:'Equipo Nova', initials:'EN', cls:'group', online:false, time:'9:28', preview:'Samuel: El sprint quedó listo', unread:0, type:'group', messages:[{from:'them', name:'Samuel', text:'El sprint quedó listo para revisión.', time:'09:17'}, {from:'me', text:'Genial equipo. Lo miro esta mañana.', time:'09:21'}, {from:'them', name:'Camila', text:'También dejé los comentarios del cliente en el tablero.', time:'09:28'}]},
      {id:'mateo', name:'Mateo Rojas', initials:'MR', cls:'a2', online:true, time:'Ayer', preview:'🎙️ Mensaje de voz · 0:18', unread:0, type:'chat', messages:[{from:'them', text:'¿A qué hora llegas?', time:'18:03'}, {from:'me', text:'En veinte minutos, aproximadamente.', time:'18:06'}, {from:'them', text:'Listo, te espero entonces.', time:'18:08'}]},
      {id:'familia', name:'Familia ♥', initials:'F', cls:'a4', online:false, time:'Ayer', preview:'Mamá: Ya llegamos a casa', unread:0, type:'group', messages:[{from:'them',name:'Mamá',text:'Ya llegamos a casa. Gracias por venir ♥',time:'20:35'}, {from:'me',text:'Me alegra mucho. Descansen.',time:'20:38'}]},
      {id:'valentina', name:'Valentina Cruz', initials:'VC', cls:'a3', online:false, time:'Lun', preview:'Gracias por tu ayuda 🙌', unread:0, type:'chat', messages:[{from:'them',text:'Gracias por tu ayuda 🙌',time:'16:12'}]},
      {id:'diseno', name:'Diseño & Café', initials:'D&C', cls:'group', online:false, time:'Vie', preview:'Tú: Me gusta esa dirección', unread:0, type:'group', messages:[{from:'me',text:'Me gusta esa dirección para el concepto.',time:'17:54'}]}
    ];
    const stateItems = [
      {name:'Mi estado', initials:'YO', cls:'a2', text:'Toca para añadir una actualización', own:true},
      {name:'Mateo Rojas', initials:'MR', cls:'a2', text:'Hoy, 09:12'}, {name:'Valentina Cruz', initials:'VC', cls:'a3', text:'Hoy, 08:40'}, {name:'Camila Torres', initials:'CT', cls:'a5', text:'Ayer, 20:14'}
    ];
    const callItems = [{name:'Mateo Rojas', initials:'MR', cls:'a2', text:'Saliente · ayer, 18:21', video:false}, {name:'Equipo Nova', initials:'EN', cls:'group', text:'Videollamada grupal · ayer, 12:05', video:true}, {name:'Laura Medina', initials:'LM', cls:'a1', text:'Entrante · lunes, 09:20', video:false}];
    let activeId = 'laura', activeTab = 'chats', callTimer, seconds = 0;
    const $ = s => document.querySelector(s); const esc = s => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
    const activeChat = () => chats.find(c=>c.id===activeId);
    function avatar(item, big=false) { return `<div class="avatar ${item.cls||''} ${big?'large':''}">${esc(item.initials||item.name.slice(0,2).toUpperCase())}${item.online?'<span class="online-dot"></span>':''}</div>`; }
    function renderList() {
      const target = $('#contactList'), query = $('#searchInput').value.trim().toLowerCase();
      if(activeTab === 'chats') {
        const filtered = chats.filter(c=>c.name.toLowerCase().includes(query)||c.preview.toLowerCase().includes(query));
        target.innerHTML = `<div class="list-label">Conversaciones</div>${filtered.map(c=>`<article class="chat-item ${c.id===activeId?'active':''}" data-chat="${c.id}">${avatar(c)}<div class="item-main"><div class="item-top"><span class="item-name">${esc(c.name)}</span><span class="item-time">${c.time}</span></div><div class="item-preview"><span>${esc(c.preview)}</span>${c.unread?`<span class="unread">${c.unread}</span>`:''}</div></div></article>`).join('') || `<div class="empty-panel"><h2>Sin resultados</h2><p>Prueba con otro nombre o inicia una conversación.</p></div>`}`;
      } else if(activeTab === 'states') {
        target.innerHTML = `<div class="list-label">Estados</div>${stateItems.filter(s=>s.name.toLowerCase().includes(query)).map(s=>`<article class="chat-item state-item" data-state="${esc(s.name)}">${avatar(s)}<div class="item-main"><div class="item-name">${esc(s.name)}</div><div class="item-preview"><span>${esc(s.text)}</span></div></div></article>`).join('')}`;
      } else {
        target.innerHTML = `<div class="list-label">Recientes</div>${callItems.filter(c=>c.name.toLowerCase().includes(query)).map((c,i)=>`<article class="chat-item call-item" data-call="${i}">${avatar(c)}<div class="item-main"><div class="item-name">${esc(c.name)}</div><div class="item-preview"><span>${esc(c.text)}</span></div></div><button class="icon-btn mini-call" title="Llamar"><svg class="icon">${c.video?'<rect x="3" y="6" width="12" height="12" rx="2"/><path d="m15 10 5-3v10l-5-3"/>':'<path d="M22 16.9v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.9.33 1.77.62 2.62a2 2 0 0 1-.45 2.11L8 9.73a16 16 0 0 0 6 6l1.28-1.28a2 2 0 0 1 2.11-.45c.85.29 1.72.5 2.62.62A2 2 0 0 1 22 16.9Z"/>'}</svg></button></article>`).join('')}`;
      }
      document.querySelectorAll('[data-chat]').forEach(el=>el.onclick=()=>openChat(el.dataset.chat));
      document.querySelectorAll('.state-item').forEach(el=>el.onclick=()=>showToast(el.dataset.state==='Mi estado'?'Aquí podrás crear tu próximo estado.':'Estado de '+el.dataset.state));
      document.querySelectorAll('[data-call]').forEach(el=>el.onclick=()=>startCall(callItems[+el.dataset.call]));
    }
    function renderChat() {
      const c = activeChat(); if(!c) return;
      $('#headerAvatar').className = `avatar ${c.cls} large`; $('#headerAvatar').innerHTML = `${esc(c.initials)}${c.online?'<span class="online-dot"></span>':''}`;
      $('#headerName').textContent = c.name; $('#headerStatus').textContent = c.online?'en línea':c.type==='group'?'8 participantes':'visto recientemente';
      $('#messages').innerHTML = `<div class="day-divider">Hoy</div>${c.messages.map(m=>`<div class="message-row ${m.from==='me'?'me':'them'}">${m.from==='them'?`<div class="mini-avatar avatar ${c.cls}">${esc(c.initials)}</div>`:''}<div class="bubble">${m.name?`<b style="font-size:10px;color:#cebaff;display:block;margin-bottom:3px">${esc(m.name)}</b>`:''}${m.file?`<div class="file-card"><div class="file-icon">▤</div><div><b>${esc(m.text)}</b><small>${esc(m.sub)}</small></div></div>`:esc(m.text)}<span class="message-meta">${m.time}${m.from==='me'?'<span class="ticks">✓✓</span>':''}</span></div></div>`).join('')}`;
      $('#messages').scrollTop = $('#messages').scrollHeight; renderList();
    }
    function openChat(id) { activeId=id; activeTab='chats'; document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab==='chats')); chats.find(c=>c.id===id).unread=0; renderChat(); $('#app').classList.add('chat-open'); }
    function sendMessage(e) { if(e) e.preventDefault(); const input=$('#messageInput'), text=input.value.trim(); if(!text) return; const c=activeChat(); c.messages.push({from:'me', text, time:new Date().toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}); c.preview='Tú: '+text; c.time='ahora'; input.value=''; renderChat(); setTimeout(()=>autoReply(c), 850); }
    function autoReply(c) { if(c.id !== activeId) return; $('#typing').classList.add('show'); setTimeout(()=>{ const replies = c.type==='group'?['¡De acuerdo!','Quedó súper claro, gracias.','Lo reviso y les cuento.']:['¡Qué buena idea!','Perfecto, gracias por avisarme.','Listo, te leo.','Me parece genial ✨']; c.messages.push({from:'them',text:replies[Math.floor(Math.random()*replies.length)],time:new Date().toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}); c.preview=c.messages[c.messages.length-1].text; c.time='ahora'; c.unread=0; $('#typing').classList.remove('show'); renderChat(); }, 1200); }
    function showToast(text) { const t=$('#toast'); t.textContent=text; t.classList.add('show'); clearTimeout(t._timer); t._timer=setTimeout(()=>t.classList.remove('show'),2800); }
    function openModal(title='Nuevo chat', text='Busca a una persona o crea un grupo para comenzar una nueva conversación.', action='Crear chat') { $('#modalTitle').textContent=title; $('#modalText').textContent=text; $('#modalPrimary').textContent=action; $('#newChatName').value=''; $('#modalBackdrop').classList.add('open'); setTimeout(()=>$('#newChatName').focus(),150); }
    function closeModal(){ $('#modalBackdrop').classList.remove('open'); }
    function createChat(){ const name=$('#newChatName').value.trim(); if(!name) return showToast('Escribe un nombre para continuar.'); const words=name.split(/\s+/); const item={id:'custom'+Date.now(),name,initials:words.map(w=>w[0]).join('').slice(0,2).toUpperCase(),cls:'a6',online:true,time:'ahora',preview:'Conversación creada',unread:0,type:'chat',messages:[{from:'them',text:'¡Hola! Esta es una nueva conversación en NovaChat.',time:'ahora'}]}; chats.unshift(item); closeModal(); openChat(item.id); showToast('Chat creado con '+name); }
    function startCall(person=activeChat(), video=false) { if(!person) return; $('#callAvatar').className=`avatar ${person.cls}`; $('#callAvatar').textContent=person.initials; $('#callName').textContent=person.name; $('#callState').textContent=video?'Iniciando videollamada...':'Llamando...'; $('#callDuration').textContent='00:00'; seconds=0; $('#callScreen').classList.add('open'); setTimeout(()=>{if($('#callScreen').classList.contains('open')) {$('#callState').textContent=video?'Videollamada en curso':'Llamada en curso'; callTimer=setInterval(()=>{seconds++;$('#callDuration').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000);}},900); }
    function endCall(){ clearInterval(callTimer); $('#callScreen').classList.remove('open'); showToast('Llamada finalizada'); }
    document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{activeTab=tab.dataset.tab; document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab)); renderList();}));
    $('#searchInput').addEventListener('input',renderList); $('#composer').addEventListener('submit',sendMessage); $('#newChatBtn').onclick=()=>openModal(); $('#topNewChat').onclick=()=>openModal(); $('#closeModal').onclick=closeModal; $('#cancelModal').onclick=closeModal; $('#modalPrimary').onclick=createChat; $('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop')) closeModal()}; $('#newChatName').addEventListener('keydown',e=>{if(e.key==='Enter')createChat()});
    $('#backBtn').onclick=()=>$('#app').classList.remove('chat-open'); $('#callBtn').onclick=()=>startCall(); $('#videoBtn').onclick=()=>startCall(activeChat(),true); $('#endCallBtn').onclick=endCall; $('#muteBtn').onclick=e=>{e.currentTarget.classList.toggle('active');showToast(e.currentTarget.classList.contains('active')?'Micrófono silenciado':'Micrófono activado')}; $('#speakerBtn').onclick=e=>{e.currentTarget.classList.toggle('active');showToast(e.currentTarget.classList.contains('active')?'Altavoz activado':'Altavoz desactivado')};
    $('#attachBtn').onclick=()=>showToast('Adjuntar archivos estará disponible en la versión funcional.'); $('#emojiBtn').onclick=()=>{const i=$('#messageInput'); i.value+=(i.value?' ':'')+'✨';i.focus()}; $('#infoBtn').onclick=()=>showToast('Perfil de '+activeChat().name); $('#settingsBtn').onclick=()=>showToast('Ajustes de NovaChat');
    renderList(); renderChat();
